add_self_loop: false
agg: mean
batch_size: 512
best_model_path: checkpoints/val_None/LA-SAGE-S/bridge/2026-05-20_13-08-06/best_val_model_None.pth
data_dir: datasets/
dataset: bridge
dataset_seed: 717
dropout: 0.2
epochs: 120
eval_interval: 1
flush_seconds: 60
focal_gamma: 2.0
focal_loss: true
force_reload: false
full_neighbors: true
gpu_id: 0
hid_dim: 40
homo: false
hyper_file: config/
log_dir: logs/
lr: 0.01
lr_scheduler: false
model: LA-SAGE-S
model_name: LA-SAGE-S
monitor: ap_gnn
multirun: 1
n_layer: 1
no_dev: false
norm_feat: false
num_trans: 1
num_workers: 8
optimizer: Adam
patience: 25
proj: true
ranking_alpha: 0.5
ranking_margin: 1.0
reduction: mean
relation_agg: cat
resi: 0.2
run_best: false
sampled_neighbors:
- -1
- -1
- -1
sampling_type: in
seed: 1234
test_each_epoch: false
thres: 0.5
threshold_moving: true
train_size: 0.6
val_size: 0.2
weight_decay: 0.001
weighted_loss: false
